language: node_js
node_js:
  - "10"
branches:
  only:
    - master

before_install:
  - git clone https://github.com/hexojs/hexo-theme-unit-test generate_test
  - git clone https://github.com/ike-c/hexo-theme-inside.git generate_test/themes/landscape
  - cd generate_test
  - npm install
  - hexo g & hexo g
  - cd ..
